### PR TITLE
Update migration.js, fix unhandled error

### PR DESCRIPTION
**Pull request by odykyi**
## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-connector-mysql) 👈

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html)
- [ ] Commit messages are following our [guidelines](https://loopback.io/doc/en/contrib/git-commit-messages.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by odykyi** [comment]
ok to test

**Comment by dhmlau** [comment]
@odykyi, thanks for your PR. Could you please sign the CLA https://cla.strongloop.com/agreements/strongloop/loopback-connector-mysql and rebase your PR? Thanks!

**Comment by dhmlau** [comment]
We just switch the contribution method from CLA to DCO, making your contribution easier in the future. Please sign the commits with DCO by amending your commit messages with `-s` flag and push the changes again. If you're using the command line, you can:

```
git commit --amend -s
git push --force-with-lease
```

Please refer to [this docs page](https://loopback.io/doc/en/contrib/code-contrib.html#developer-certificate-of-origin-dco) for details. Thanks! 

For more questions, please join our [Slack workspace - #loopback-contributors](https://loopbackio.slack.com/join/shared_invite/zt-8lbow73r-SKAKz61Vdao~_rGf91pcsw#/).

**Pull request closed without merging**
